<?php
// content fields test

function website_acf_add_local_field_groups(){
	acf_add_local_field_group(
		[
			'key' => 'group_1',
			'title' => __('Contents', website_textdomain()),
			'fields' => [
				[
					'key' => 'modules',
					'label' => 'Module',
					'name' => 'modules',
					'type' => 'flexible_content',
				]
			],
			'location' => [
				[
					[
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
					]
				],
				[
					[
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'page',
					]
				]
			],
		]
	);
}

add_action('acf/init', 'website_acf_add_local_field_groups');

/*
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_5fda338ca0071',
	'title' => 'Inhalte',
	'fields' => array(
		array(
			'key' => 'field_5fda370d3249b',
			'label' => 'Module',
			'name' => 'modules',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 3,
			'layouts' => array(
				'layout_5fda372b25d75' => array(
					'key' => 'layout_5fda372b25d75',
					'name' => 'stage-home',
					'label' => 'Stage Home',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_62ced06e6919f',
							'label' => 'Hintergrundbild',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_6408ad2d26d24',
							'label' => 'Video',
							'name' => 'video',
							'aria-label' => '',
							'type' => 'file',
							'instructions' => 'Hintergrundbild wird als Vorschaubild verwendet',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_62ced085691a0',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_6478aec6adb43',
							'label' => 'Logo (SVG-Code)',
							'name' => 'logo-svg',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64873a031f907' => array(
					'key' => 'layout_64873a031f907',
					'name' => 'stage',
					'label' => 'Stage',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64873a171f909',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64873a301f90a',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64873a3f1f90b',
							'label' => 'Hintergrundbild',
							'name' => 'background-image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5fda37383249c' => array(
					'key' => 'layout_5fda37383249c',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_62d162d0fd597',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_62da9b371122c',
							'label' => 'Hintergrundfarbe',
							'name' => 'background-color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'choices' => array(
								'default' => 'Standard',
								'black' => 'Schwarz',
								'white' => 'Weiß',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_647e0cd0d2e7c' => array(
					'key' => 'layout_647e0cd0d2e7c',
					'name' => 'teaser',
					'label' => 'Teaser (Verlinkungen auf Unterseiten, z.B. "Mehr über FidCap")',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_647e0cfdd2e7e',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_647e0d0ed2e7f',
							'label' => 'Teaser',
							'name' => 'teaser',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_647e0d56d2e82',
									'label' => 'Titel / Link',
									'name' => 'link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'parent_repeater' => 'field_647e0d0ed2e7f',
								),
								array(
									'key' => 'field_647e0d3dd2e81',
									'label' => 'Beschreibung',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_647e0d0ed2e7f',
								),
								array(
									'key' => 'field_647e0e570ab9a',
									'label' => 'Hintergrundbild',
									'name' => 'background-image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_647e0d0ed2e7f',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64887506e9e27' => array(
					'key' => 'layout_64887506e9e27',
					'name' => 'founder',
					'label' => 'Gründer (Einleitungstext mit Bild, Vita)',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6488753de9e29',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64887573e9e2b',
							'label' => 'Text, Bild',
							'name' => 'text-image',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_6488755ee9e2a',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 0,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array(
									'key' => 'field_648875a9e9e2c',
									'label' => 'Bild',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
								),
							),
						),
						array(
							'key' => 'field_648877620afcb',
							'label' => 'Vita Überschrift',
							'name' => 'vita-headline',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_648875d2e9e2d',
							'label' => 'Vita',
							'name' => 'vita',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_648875f7e9e2e',
									'label' => 'Text links',
									'name' => 'text-left',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => 'Auflistung',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
								array(
									'key' => 'field_6488762fe9e2f',
									'label' => 'Text rechts',
									'name' => 'text-right',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6489aa0aab161' => array(
					'key' => 'layout_6489aa0aab161',
					'name' => 'text-on-image',
					'label' => 'Text auf Bild',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6489aa0aab163',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6489aa0aab164',
							'label' => 'Hintergrundbild',
							'name' => 'background-image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_64b950d85a7d4',
							'label' => 'Hintergrundfarbe',
							'name' => 'background-color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'choices' => array(
								'default' => 'Schwarz',
								'transparent' => 'Transparent',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6489aa8263232' => array(
					'key' => 'layout_6489aa8263232',
					'name' => 'our-engagement',
					'label' => 'Unser Engagement (Einleitungstext, Icons/Text in 3 Spalten, Logos)',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6489aab963234',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6489aae763235',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6489ab0563236',
							'label' => 'Icon und Text in 3 Spalten',
							'name' => 'icon-and-text',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6489ab4263237',
									'label' => 'Icon',
									'name' => 'icon',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_6489ab0563236',
								),
								array(
									'key' => 'field_6489ab5163238',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_6489ab0563236',
								),
							),
						),
						array(
							'key' => 'field_6489ab6a63239',
							'label' => 'Logos',
							'name' => 'logos',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6489ab796323a',
									'label' => 'image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_6489ab6a63239',
								),
								array(
									'key' => 'field_6489ab886323b',
									'label' => 'Link',
									'name' => 'link',
									'aria-label' => '',
									'type' => 'link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'parent_repeater' => 'field_6489ab6a63239',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6489abde490a1' => array(
					'key' => 'layout_6489abde490a1',
					'name' => 'link-to-next-page',
					'label' => 'Mehr über uns (Link auf weitere Seite)',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6489ac04490a3',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6489ac14490a4',
							'label' => 'Link',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
						),
						array(
							'key' => 'field_6495af44129b6',
							'label' => 'Hintergrundfarbe',
							'name' => 'background-color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'choices' => array(
								'default' => 'Standard',
								'grey2' => 'Grau 2 (#D9D9D9)',
								'black' => 'Schwarz',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64932995eb76f' => array(
					'key' => 'layout_64932995eb76f',
					'name' => 'text-with-big-headline',
					'label' => 'Text mit großer Headline',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64932995eb770',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64932995eb772',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_64932a3aeb778',
							'label' => 'Hintergrundfarbe',
							'name' => 'background-color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'choices' => array(
								'default' => 'Standard',
								'black' => 'Schwarz',
								'white' => 'Weiß',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64a809a636527' => array(
					'key' => 'layout_64a809a636527',
					'name' => 'jobs-text-with-big-headline',
					'label' => 'Jobs - Text mit großer Headline',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a809a636528',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64a809a636529',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_64a809a63652a',
							'label' => 'Hintergrundfarbe',
							'name' => 'background-color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'choices' => array(
								'default' => 'Standard',
								'black' => 'Schwarz',
								'white' => 'Weiß',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64940826909b7' => array(
					'key' => 'layout_64940826909b7',
					'name' => 'project-development',
					'label' => 'Projektentwicklung / Geschäftsfelder',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64940850909b9',
							'label' => 'Einträge',
							'name' => 'entries',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_64940879909ba',
									'label' => 'Titel',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_64940850909b9',
								),
								array(
									'key' => 'field_64940889909bb',
									'label' => 'Beschreibung',
									'name' => 'description',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_64940850909b9',
								),
								array(
									'key' => 'field_649408a4909bc',
									'label' => 'Nummer',
									'name' => 'number',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '20',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_64940850909b9',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649594d51c5ee' => array(
					'key' => 'layout_649594d51c5ee',
					'name' => 'investments',
					'label' => 'Investments (Anforderungsprofil)',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_649594d51c5ef',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_649594d51c5f0',
							'label' => 'Hintergrundbild',
							'name' => 'background-image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_6495950f1c5f1',
							'label' => 'Text in Kreisen',
							'name' => 'text-in-circles',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'row',
							'min' => 0,
							'max' => 4,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6495953b1c5f2',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 0,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_6495950f1c5f1',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649aebbfac871' => array(
					'key' => 'layout_649aebbfac871',
					'name' => 'project-overview',
					'label' => 'Projektübersicht',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a594a381875',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649aebd8ac873',
							'label' => 'Anzahl',
							'name' => 'count',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => 6,
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649aebfdac874',
							'label' => '"Mehr laden"-Text',
							'name' => 'load-more-text',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => 'Load more',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64994fa271376' => array(
					'key' => 'layout_64994fa271376',
					'name' => 'project-stage',
					'label' => 'Projekt-Stage',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64994fa271377',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64994fc77137a',
							'label' => 'Link zu Google Maps',
							'name' => 'link-to-google-maps',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
						),
						array(
							'key' => 'field_64994fa271379',
							'label' => 'Hintergrundbild',
							'name' => 'background-image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 1,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649952777137e' => array(
					'key' => 'layout_649952777137e',
					'name' => 'project-data',
					'label' => 'Projekt-Daten',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6499528671380',
							'label' => 'Daten',
							'name' => 'data',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6499529a71381',
									'label' => 'Überschrift',
									'name' => 'headline',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'rows' => 2,
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_6499528671380',
								),
								array(
									'key' => 'field_649952b371382',
									'label' => 'Wert',
									'name' => 'value',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'rows' => 2,
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_6499528671380',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649952ee71383' => array(
					'key' => 'layout_649952ee71383',
					'name' => 'project-text',
					'label' => 'Projekt-Text',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6499531071385',
							'label' => 'Linke Spalte',
							'name' => 'left-column',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_6499534a71386',
									'label' => 'Überschrift',
									'name' => 'headline',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => '',
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6499535871387',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => '',
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
						array(
							'key' => 'field_6499536b71388',
							'label' => 'Rechte Spalte',
							'name' => 'right-column',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_6499536b71389',
									'label' => 'Überschrift',
									'name' => 'headline',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6499538a7138b',
									'label' => 'Spalten-Inhalte',
									'name' => 'column-contents',
									'aria-label' => '',
									'type' => 'flexible_content',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 3,
									'layouts' => array(
										'layout_64995399145e8' => array(
											'key' => 'layout_64995399145e8',
											'name' => 'logo',
											'label' => 'Logo',
											'display' => 'row',
											'sub_fields' => array(
												array(
													'key' => 'field_649953cb7138c',
													'label' => 'Logo',
													'name' => 'logo',
													'aria-label' => '',
													'type' => 'image',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'wpml_cf_preferences' => 2,
													'return_format' => 'array',
													'library' => 'all',
													'min_width' => '',
													'min_height' => '',
													'min_size' => '',
													'max_width' => '',
													'max_height' => '',
													'max_size' => '',
													'mime_types' => '',
													'preview_size' => 'medium',
												),
											),
											'min' => '',
											'max' => '',
										),
										'layout_649953de7138d' => array(
											'key' => 'layout_649953de7138d',
											'name' => 'text',
											'label' => 'Text',
											'display' => 'row',
											'sub_fields' => array(
												array(
													'key' => 'field_649953e97138f',
													'label' => 'Text',
													'name' => 'text',
													'aria-label' => '',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'wpml_cf_preferences' => 2,
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 1,
													'delay' => 0,
												),
											),
											'min' => '',
											'max' => '',
										),
									),
									'min' => '',
									'max' => '',
									'button_label' => 'Eintrag hinzufügen',
								),
							),
						),
						array(
							'key' => 'field_649957c869c29',
							'label' => 'Überschrift "zur Projektwebsite"',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => 'Zur Projektwebsite',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6499546671391',
							'label' => 'Link zur Projektwebseite',
							'name' => 'link-to-project-page',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649954d6f54d0' => array(
					'key' => 'layout_649954d6f54d0',
					'name' => 'project-impressions',
					'label' => 'Projektimpressionen',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_649954f9f54d2',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6499550bf54d3',
							'label' => 'Bilder',
							'name' => 'images',
							'aria-label' => '',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 1,
							'return_format' => 'array',
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'insert' => 'append',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649d50f0ed124' => array(
					'key' => 'layout_649d50f0ed124',
					'name' => 'news',
					'label' => 'News',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_649d5111ed126',
							'label' => 'Bild',
							'name' => 'image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_649d511ded127',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_649ea4dbfde7d' => array(
					'key' => 'layout_649ea4dbfde7d',
					'name' => 'news-overview',
					'label' => 'News-Übersicht',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_649ea4f7fde7f',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649ea503fde80',
							'label' => 'Anzahl',
							'name' => 'count',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649ea512fde81',
							'label' => '"Mehr laden" - Text',
							'name' => 'load-more-text',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => 'Load more',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64a2cbbced0bc' => array(
					'key' => 'layout_64a2cbbced0bc',
					'name' => 'jobs',
					'label' => 'Stellengesuche',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a2cecb8ff67',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64a2cbc6ed0be',
							'label' => 'Ausschreibung',
							'name' => 'offer',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_64a2cbefed0bf',
									'label' => 'Titel',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_64a2cbc6ed0be',
								),
								array(
									'key' => 'field_64a2cc15ed0c0',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_64a2cbc6ed0be',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64a2f9b2b0637' => array(
					'key' => 'layout_64a2f9b2b0637',
					'name' => 'application-contact',
					'label' => 'Bewerbungskontakt',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a2facd61a58',
							'label' => 'Titel',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_64a2f9b2b0638',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64a2f9b2b0639',
							'label' => 'Hintergrundbild',
							'name' => 'background-image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64a4307d7109b' => array(
					'key' => 'layout_64a4307d7109b',
					'name' => 'contact-stage',
					'label' => 'Kontakt-Stage',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a4307d7109d',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64a430d7fc425',
							'label' => 'Elemente',
							'name' => 'elements',
							'aria-label' => '',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layouts' => array(
								'layout_64a4311eb9d4c' => array(
									'key' => 'layout_64a4311eb9d4c',
									'name' => 'text-in-2-columns',
									'label' => 'Text in 2 Spalten',
									'display' => 'row',
									'sub_fields' => array(
										array(
											'key' => 'field_64a4317bfc426',
											'label' => 'Überschrift',
											'name' => 'headline',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'wpml_cf_preferences' => 2,
											'default_value' => '',
											'maxlength' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
										),
										array(
											'key' => 'field_64a43189fc427',
											'label' => 'Texts',
											'name' => 'texts',
											'aria-label' => '',
											'type' => 'group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'wpml_cf_preferences' => 3,
											'layout' => 'table',
											'sub_fields' => array(
												array(
													'key' => 'field_64a431a6fc428',
													'label' => 'Text links',
													'name' => 'text-left',
													'aria-label' => '',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'wpml_cf_preferences' => 2,
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 0,
													'delay' => 0,
												),
												array(
													'key' => 'field_64a431b9fc429',
													'label' => 'Text right',
													'name' => 'text-right',
													'aria-label' => '',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'wpml_cf_preferences' => 2,
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 0,
													'delay' => 0,
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
								'layout_64a431d0fc42a' => array(
									'key' => 'layout_64a431d0fc42a',
									'name' => 'links',
									'label' => 'Links',
									'display' => 'row',
									'sub_fields' => array(
										array(
											'key' => 'field_64a431dcfc42c',
											'label' => 'Links',
											'name' => 'links',
											'aria-label' => '',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'wpml_cf_preferences' => 3,
											'layout' => 'row',
											'min' => 0,
											'max' => 0,
											'collapsed' => '',
											'button_label' => 'Eintrag hinzufügen',
											'rows_per_page' => 20,
											'sub_fields' => array(
												array(
													'key' => 'field_64a431fafc42d',
													'label' => 'Link',
													'name' => 'link',
													'aria-label' => '',
													'type' => 'link',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'wpml_cf_preferences' => 2,
													'return_format' => 'array',
													'parent_repeater' => 'field_64a431dcfc42c',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'min' => '',
							'max' => '',
							'button_label' => 'Eintrag hinzufügen',
						),
						array(
							'key' => 'field_64a4307d7109e',
							'label' => 'Hintergrundbild',
							'name' => 'background-image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64a5574ff797d' => array(
					'key' => 'layout_64a5574ff797d',
					'name' => 'form',
					'label' => 'Formular',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a55757f797f',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64a559cef7980',
							'label' => 'Formular',
							'name' => 'form',
							'aria-label' => '',
							'type' => 'acf_cf7',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_64a57c4d1bd40',
							'label' => 'Datenschutz-Text',
							'name' => 'privacy-policy-text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64a58b637dfb9' => array(
					'key' => 'layout_64a58b637dfb9',
					'name' => 'text-imprint',
					'label' => 'Text (Impressum, Datenschutz)',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64a58b637dfba',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64ba84a5ee592' => array(
					'key' => 'layout_64ba84a5ee592',
					'name' => 'esg-values',
					'label' => 'ESG Werte',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64c0e1defab06',
							'label' => 'Überschrift',
							'name' => 'headline',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64ba84b3ee594',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64ba84d9ee595',
							'label' => 'Werte',
							'name' => 'values',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_64ba8555ee596',
									'label' => 'Bild',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_64ba84d9ee595',
								),
								array(
									'key' => 'field_64ba8570ee597',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_64ba84d9ee595',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_64ba85cce24b8' => array(
					'key' => 'layout_64ba85cce24b8',
					'name' => 'certificates',
					'label' => 'Zertifikate',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_64ba8635e24bd',
							'label' => 'Text',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64ba8603e24bc',
							'label' => 'Zertifikate',
							'name' => 'certificates',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 3,
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Eintrag hinzufügen',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_64ba85d8e24ba',
									'label' => 'Bild',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_64ba8603e24bc',
								),
								array(
									'key' => 'field_64ba85eee24bb',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_64ba8603e24bc',
								),
								array(
									'key' => 'field_64ba868fe24be',
									'label' => 'Titel in grüner Box',
									'name' => 'title-in-green-box',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'maxlength' => '',
									'rows' => 2,
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_64ba8603e24bc',
								),
								array(
									'key' => 'field_64ba86aee24bf',
									'label' => 'Text in grüner Box',
									'name' => 'text-in-green-box',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'wpml_cf_preferences' => 2,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 0,
									'delay' => 0,
									'parent_repeater' => 'field_64ba8603e24bc',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Add Row',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'projects',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'comments',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfml_field_group_mode' => 'advanced',
) );
} );

*/


